### ISSUE TITLE
Add other methods to vignette illustration of `simple_ensemble`

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubEnsembles#16]
Current draft vignette includes an example of calculating an ensemble using a simple mean. We could also add examples of other aggregation functions (`agg_fun`):

- `"median"`
- weighted mean
- weighted median
- a custom `agg_fun`. I'm open to ideas here. Maybe a geometric mean, just to get something that's different but plausible?

**Comment by nickreich** [comment]
I think many of these suggestions have been incorporated [here](https://infectious-disease-modeling-hubs.github.io/hubEnsembles/articles/hubEnsembles.html) already. Can we close this? @elray1 @eahowerton @lshandross

**Comment by elray1** [comment]
sounds good to me
