### ISSUE TITLE
readme for github repository

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubEnsembles#18]
We should add content to the `README.Rmd` file in this repository and render it to get a `README.md`

**Comment by nickreich** [comment]
I directly pushed a first pass at a README.md file, although I left this issue open because I think we might want more content here at some point. Maybe at least a link to the forthcoming pkgdown site?

**Comment by nickreich** [comment]
I am going to close this for now.
