### ISSUE TITLE
Update authors

### ISSUE THREAD

**Issue by mzorn-58** [Infectious-Disease-Modeling-Hubs/hubEnsembles#38]
Use definition below
[Definitions of roles](https://r-pkgs.org/description.html#sec-description-authors-at-r) (Author, maintainer, contributor, etc…)

Going forward, ensure that PRs from new contributors include an update to authorship roles (for R packages, in description file)

**Comment by nickreich** [comment]
Noting that based on current contributors, @nickreich and @eahowerton should be added to the DESCRIPTION file.

**Comment by annakrystalli** [comment]
I'm planning to downgrade myself to just a contributor here  .

Would you be happy with being author and maintainer @lshandross? Let me know of any other changes to authors list you might want too

**Comment by annakrystalli** [comment]
@eahowerton do you have an ORCID you would like me to add for you in the DESCRIPTION?

**Comment by lshandross** [comment]
@annakrystalli Fine with me! Would you mind also adding my ORCID 0009-0008-1348-1954?

**Comment by eahowerton** [comment]
@annakrystalli thanks for doing this! My ORCID is https://orcid.org/0000-0002-0639-3728
