### ISSUE TITLE
Figure 4.1 does not reproduce

### ISSUE THREAD

**Issue by harryhoch** [Infectious-Disease-Modeling-Hubs/hubEnsembles#54]
ran the code for 4.1, bot this error:

Warning: ! `model_output_data` must be a `model_out_tbl`. Class applied by defaultError in theme_bw() : could not find function "theme_bw"

**Comment by harryhoch** [comment]
found the problem.  - wasn't including ggplot. 

added  library(ggplot2) to the example coe.

**Comment by lshandross** [comment]
Solved by https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/commit/5703ba417c7b925ec0ea98ba9599fb7ac28717ca
