### ISSUE TITLE
remove Hmisc dependency

### ISSUE THREAD

**Issue by nickreich** [Infectious-Disease-Modeling-Hubs/hubEnsembles#55]
Noting that in HubEnsembles there is one fairly simple function that is [used in one place](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/blob/80517854361312b81bce43dddf4d767d3a793b45/R/linear_pool_quantile.R#L80) from the Hmisc package. I don't know standard procedure here, but I wonder if we could simply reproduce that single function (with attribution) on our own to reduce dependencies on, well, "miscellaneous" R packages that otherwise are not core to the mission of the package.

**Comment by nickreich** [comment]
@annakrystalli I'm wondering if you have thoughts about R cultural conventions about re-using a small amount of code (with attribution) from one package to avoid dependencies.

**Comment by annakrystalli** [comment]
Yes very common and acceptable practice. Good to add a comment in the code too about it, see for example:
https://github.com/Infectious-Disease-Modeling-Hubs/hubDevs/blob/c566e5b5a60bccccbc9f038be39b529b9b8557a3/R/usethis-utils.R#L1-L12

**Comment by lshandross** [comment]
This is a package-based issue, not a manuscript one, right? Can someone else confirm before I remove the manuscript label?
