### ISSUE TITLE
Add manuscript directory to .Rbuildignore

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubEnsembles#67]
We need to tell R to ignore the manuscript directory when building the package.

Use:
```r
usethis::use_build_ignore("manuscript")
```

to do so. 

Happy to just fix this with a quick patch if you like?

**Comment by lshandross** [comment]
If you don't mind, that would be great. Thanks @annakrystalli

**Comment by annakrystalli** [comment]
Done here 🙂 https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/pull/68
