### ISSUE TITLE
once hubUtils -> hubAdmin, hubData, hubUtils is split, double check location where model_out_tbl is defined

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubEnsembles#73]
Relevant to this sentence: "This representation of predictive model output is codified by the model_out_tbl S3 class in the hubUtils package, one of the foundational hubverse packages."

May also just be worth checking in with @annakrystalli r.e. where she plans to put the definition of that class.

**Comment by annakrystalli** [comment]
Good question @elray1. It probably fits better in the `hubData` package. Having said that another solid approach would be to leave it in `hubUtils` but export relevant functions to other packages that utilise the class (a bit like `tidyselect` functions are across the tidyverse). This would be my personal preference.

In any case I think we be able to get away with not mentioning `hubUtils` explicitly with something like:
> codified by the model_out_tbl S3 class, one of the fundamental data classes across hubverse packages?

**Comment by lshandross** [comment]
Leaving this issue instead of transferring it to the new [hubEnsembles-manuscript](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles-manuscript) repo since it seems partially relevant to the main `hubEnsembles` package for when `hubUtils` is split
