### ISSUE TITLE
clarify claim about ensemble performance

### ISSUE THREAD

**Issue by elray1** [Infectious-Disease-Modeling-Hubs/hubEnsembles#87]
We write, "For example, the linear pools achieved the lowest WIS during the period of rapid change in incident flu hospitalizations surrounding the season’s peak in early December 2022."

To my eye, in this figure for horizon 4 the linear pools were never best in the months of Nov or Dec 22.  Do we want to clarify that this is a statement about horizon 1?  And "among the ensemble methods", as actually the baseline did better at horizon 1 in early Dec?

![image](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/assets/5132208/93c7fb54-2bd0-4a27-a62b-37dd2733644b)

**Comment by lshandross** [comment]
Clarified the part describing the linear pools's performance as being for horizon = 1, but from what I can tell the linear pools did generally outperform the baseline in most weeks around the 2022-2023 season peak (see attached version of the wis 2022-2023 plot for 1 week ahead). Maybe this just means the figure isn't big enough in the manuscript?

![image](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/assets/57642277/810c3302-991b-409e-8fbf-2a6758751098)

**Comment by elray1** [comment]
I agree that it would be easier to see things if the figure were a little larger -- but clarifying, I do agree with the statement for horizon 1, but it doesn't seem to hold for horizon 4 from what I could see.
