### ISSUE TITLE
Remove manuscript Rmd and its associated files

### ISSUE THREAD

**Issue by lshandross** [Infectious-Disease-Modeling-Hubs/hubEnsembles#95]
The last step of splitting out the manuscript into its own separate repo ([hubEnsemblesManuscript](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsemblesManuscript)), as we decided in [this issue](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsemblesManuscript/issues/11) which was transferred over to the new repo, is deleting all of the associated files in this original `hubEnsembles` repo. I have a couple of questions I was hoping to get others' opinions on before committing to the permanent deletion:

What exactly should we be deleting from the `hubEnsembles` repo? The entire `software-manuscript` branch? Just the `manuscript` directory on this branch? Note that all the manuscript files live on the [software-manuscript](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/tree/software-manuscript) branch in the `manuscript` directory

Feel free to add any other thoughts on manuscript deletion stuff from this repo @eahowerton @annakrystalli @elray1 @nickreich

**Comment by elray1** [comment]
Is there anything that's a part of the actual package or its documentation that's on the branch but not merged into main?  If not, I think it's fine to just delete the whole branch.

**Comment by eahowerton** [comment]
Do we want to keep the `example-complex-hub` data with the package? I believe this is only on the software-manuscript branch right now ([.rda files](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/tree/software-manuscript/data) and [corresponding scripts to generate them](https://github.com/Infectious-Disease-Modeling-Hubs/hubEnsembles/tree/software-manuscript/data-raw))

**Comment by elray1** [comment]
sure, let's keep those :) sounds like the working plan is to have data files like that within each package.

**Comment by eahowerton** [comment]
I just did a quick browse through the other diffs, and I don't see anything else that should be on main

**Comment by lshandross** [comment]
Do we want to also keep the changes to the `example-simple-hub` data (addition of mean and pmf output types) on the software-manuscript branch? I think @eahowerton originally made the changes to be used in the examples section (which would persist in the vignette), but I haven't been keeping track of whether all the examples in the manuscript have switched to using the `example-complex-hub` data.

**Comment by eahowerton** [comment]
@lshandross, you're referring to what is in the `inst` folder? I think those should be removed. What @elray1 implemented in `example-complex-forecast-hub` is a better version of my initial attempt (currently in `inst`). The pmf output type example data I had generated was entirely random, and instead the `example-complex-forecast-hub` data has pmf output type data that aligns with the corresponding quantile forecasts.

I think it'd be better to keep only the `example-complex-forcast-hub` data to avoid confusion.

**Comment by lshandross** [comment]
@eahowerton yes, thanks for the explanation. Do you mind copying the `example-complex-forecast-hub` files onto the main branch? I'm not sure how you want to structure those data files in the repo for use in the vignette, so it might be simpler for you to make the changes instead of describing the organization to me

**Comment by lshandross** [comment]
Summarizing a discussion @eahowerton and I had on Slack:

We will not yet be deleting the old `example-simple-forecast-hub` files to avoid breaking the vignette (even though it is out of date). Once the manuscript is fully finished, the vignette will be updated with the relevant sections. The larger deletion of the `software-manuscript-branch` can proceed as planned.

**Comment by elray1** [comment]
@lshandross just checking -- is this issue still active, or can it be closed?

**Comment by lshandross** [comment]
I was leaving it open because there are a couple of example data files used in the vignette that are out of date compared to what's in the manuscript now, but Emily and I thought it would be better to leave them in so the vignette doesn't break until we're ready to update the vignette when the manuscript is done.

**Comment by lshandross** [comment]
Remaining task of replacing example data with updated versions consistent with the manuscript is summarized on Issue #104, so I'm closing this issue since the other parts of it are finished
